### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [annagaiel/versuet#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by annagaiel** [comment]
Hi Ken,

I moved the mobile meta tag before the head's closing tag. I pushed it on https://versuet.herokuapp.com/.

**Comment by kenmazaika** [comment]
Thumbs up, Anna.  :+1: 

Looks solid! :)  Great work.
